// <auto-generated />
using System;
using BTPSecure.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTPSecure.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504210034_AjoutSiretSiren")]
    partial class AjoutSiretSiren
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DureeValidite")
                        .HasColumnType("integer");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("ListeMateriaux")
                        .HasColumnType("text");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PatronId")
                        .HasColumnType("integer");

                    b.Property<int>("SalarieId")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int>("TypeCode")
                        .HasColumnType("integer");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("PatronId");

                    b.HasIndex("SalarieId");

                    b.HasIndex("Valeur")
                        .IsUnique();

                    b.ToTable("codes", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstAutorisee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PatronId")
                        .HasColumnType("integer");

                    b.Property<string>("Siret")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PatronId");

                    b.ToTable("entreprises", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_SalarieEntreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("SalarieId")
                        .HasColumnType("integer");

                    b.Property<int>("StatutInvitation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("SalarieId");

                    b.ToTable("salaries_entreprises", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Sel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siren")
                        .HasColumnType("text");

                    b.Property<string>("Siret")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utilisateurs", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Code", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Patron")
                        .WithMany()
                        .HasForeignKey("PatronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Salarie")
                        .WithMany()
                        .HasForeignKey("SalarieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entreprise");

                    b.Navigation("Fournisseur");

                    b.Navigation("Patron");

                    b.Navigation("Salarie");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Entreprise", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Patron")
                        .WithMany()
                        .HasForeignKey("PatronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patron");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_SalarieEntreprise", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Salarie")
                        .WithMany()
                        .HasForeignKey("SalarieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entreprise");

                    b.Navigation("Salarie");
                });
#pragma warning restore 612, 618
        }
    }
}
