// <auto-generated />
using System;
using BTPSecure.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTPSecure.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906143409_AjoutHistoriqueValidations")]
    partial class AjoutHistoriqueValidations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Blacklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId", "Email")
                        .IsUnique();

                    b.ToTable("blacklists", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchatsSupplementaires")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("CollaborateurId")
                        .HasColumnType("integer")
                        .HasColumnName("SalarieId");

                    b.Property<int?>("CreateurId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatePrete")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DirigeantId")
                        .HasColumnType("integer")
                        .HasColumnName("PatronId");

                    b.Property<int?>("DureeValidite")
                        .HasColumnType("integer");

                    b.Property<string>("EmailTiers")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstPermanent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("EstPrete")
                        .HasColumnType("boolean");

                    b.Property<int?>("FournisseurContactId")
                        .HasColumnType("integer");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("ListeMateriaux")
                        .HasColumnType("text");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reference")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int>("TypeCode")
                        .HasColumnType("integer");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.HasIndex("CollaborateurId");

                    b.HasIndex("CreateurId");

                    b.HasIndex("DirigeantId");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("FournisseurContactId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("Valeur")
                        .IsUnique();

                    b.ToTable("codes", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_CollaborateurEntreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollaborateurId")
                        .HasColumnType("integer")
                        .HasColumnName("SalarieId");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("RoleEntreprise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("StatutInvitation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CollaborateurId");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("salaries_entreprises", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DirigeantId")
                        .HasColumnType("integer")
                        .HasColumnName("PatronId");

                    b.Property<bool>("EstAutorisee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LimiteResponsables")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Siret")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DirigeantId");

                    b.ToTable("entreprises", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_FournisseurContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DirigeantId")
                        .HasColumnType("integer")
                        .HasColumnName("PatronId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Siren")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Siret")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.HasIndex("DirigeantId", "Siret");

                    b.ToTable("fournisseurs_contacts", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Memo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("memos", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstLue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Severite")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId", "EstLue");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_ResetMotDePasse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstUtilise")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UtilisateurId");

                    b.ToTable("resets_motdepasse", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DestinataireId")
                        .HasColumnType("integer");

                    b.Property<string>("EmailDestinataire")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EstLu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("NomPieceJointe")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("PieceJointe")
                        .HasColumnType("bytea");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TypePieceJointe")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreation");

                    b.HasIndex("DestinataireId");

                    b.HasIndex("ExpediteurId");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailVerifie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("EstValide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("LimiteSousComptes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomSociete")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentFournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Sel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siren")
                        .HasColumnType("text");

                    b.Property<string>("Siret")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenVerification")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("TokenVerificationExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ParentFournisseurId");

                    b.HasIndex("TokenVerification");

                    b.ToTable("utilisateurs", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_ValidationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchatsSupplementaires")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("CodeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailTiers")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstPermanent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PorteurId")
                        .HasColumnType("integer");

                    b.Property<string>("ValeurUtilisee")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("ValidateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("PorteurId");

                    b.HasIndex("ValidateurId");

                    b.HasIndex("EntrepriseId", "DateValidation");

                    b.ToTable("validations_codes", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Blacklist", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Code", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Collaborateur")
                        .WithMany()
                        .HasForeignKey("CollaborateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Dirigeant")
                        .WithMany()
                        .HasForeignKey("DirigeantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_FournisseurContact", "FournisseurContact")
                        .WithMany()
                        .HasForeignKey("FournisseurContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Collaborateur");

                    b.Navigation("Createur");

                    b.Navigation("Dirigeant");

                    b.Navigation("Entreprise");

                    b.Navigation("Fournisseur");

                    b.Navigation("FournisseurContact");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_CollaborateurEntreprise", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Collaborateur")
                        .WithMany()
                        .HasForeignKey("CollaborateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collaborateur");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Entreprise", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Dirigeant")
                        .WithMany()
                        .HasForeignKey("DirigeantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dirigeant");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_FournisseurContact", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Dirigeant")
                        .WithMany()
                        .HasForeignKey("DirigeantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dirigeant");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Memo", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Notification", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_ResetMotDePasse", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Ticket", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Destinataire")
                        .WithMany()
                        .HasForeignKey("DestinataireId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Expediteur")
                        .WithMany()
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destinataire");

                    b.Navigation("Expediteur");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Utilisateur", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("ParentFournisseurId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_ValidationCode", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Code", "Code")
                        .WithMany()
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Porteur")
                        .WithMany()
                        .HasForeignKey("PorteurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Validateur")
                        .WithMany()
                        .HasForeignKey("ValidateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Code");

                    b.Navigation("Porteur");

                    b.Navigation("Validateur");
                });
#pragma warning restore 612, 618
        }
    }
}
