// <auto-generated />
using System;
using BTPSecure.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTPSecure.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollaborateurId")
                        .HasColumnType("integer")
                        .HasColumnName("SalarieId");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatePrete")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DirigeantId")
                        .HasColumnType("integer")
                        .HasColumnName("PatronId");

                    b.Property<int?>("DureeValidite")
                        .HasColumnType("integer");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstPrete")
                        .HasColumnType("boolean");

                    b.Property<int?>("FournisseurContactId")
                        .HasColumnType("integer");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("ListeMateriaux")
                        .HasColumnType("text");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reference")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int>("TypeCode")
                        .HasColumnType("integer");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.HasIndex("CollaborateurId");

                    b.HasIndex("DirigeantId");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("FournisseurContactId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("Valeur")
                        .IsUnique();

                    b.ToTable("codes", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_CollaborateurEntreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollaborateurId")
                        .HasColumnType("integer")
                        .HasColumnName("SalarieId");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("StatutInvitation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CollaborateurId");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("salaries_entreprises", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DirigeantId")
                        .HasColumnType("integer")
                        .HasColumnName("PatronId");

                    b.Property<bool>("EstAutorisee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Siret")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DirigeantId");

                    b.ToTable("entreprises", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_FournisseurContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DirigeantId")
                        .HasColumnType("integer")
                        .HasColumnName("PatronId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Siren")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Siret")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.HasIndex("DirigeantId", "Siret");

                    b.ToTable("fournisseurs_contacts", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_ResetMotDePasse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstUtilise")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UtilisateurId");

                    b.ToTable("resets_motdepasse", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailVerifie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Sel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siren")
                        .HasColumnType("text");

                    b.Property<string>("Siret")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenVerification")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("TokenVerificationExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TokenVerification");

                    b.ToTable("utilisateurs", (string)null);
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Code", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Collaborateur")
                        .WithMany()
                        .HasForeignKey("CollaborateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Dirigeant")
                        .WithMany()
                        .HasForeignKey("DirigeantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_FournisseurContact", "FournisseurContact")
                        .WithMany()
                        .HasForeignKey("FournisseurContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Collaborateur");

                    b.Navigation("Dirigeant");

                    b.Navigation("Entreprise");

                    b.Navigation("Fournisseur");

                    b.Navigation("FournisseurContact");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_CollaborateurEntreprise", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Collaborateur")
                        .WithMany()
                        .HasForeignKey("CollaborateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTPSecure.Shared.Entites.E_Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collaborateur");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_Entreprise", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Dirigeant")
                        .WithMany()
                        .HasForeignKey("DirigeantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dirigeant");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_FournisseurContact", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Dirigeant")
                        .WithMany()
                        .HasForeignKey("DirigeantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dirigeant");
                });

            modelBuilder.Entity("BTPSecure.Shared.Entites.E_ResetMotDePasse", b =>
                {
                    b.HasOne("BTPSecure.Shared.Entites.E_Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
